name: Validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: PeterJCLaw/srcomp-validate-action@bd809ff12b77607cc2f0ebbd035d6f0a5c8d32fc
