name: Validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: PeterJCLaw/srcomp-validate-action@4a3c67770703a7abce85ca66a56a7acfcb2f4c42
